version: '3.8'
services:
  web1:
    build: ./web1
    container_name: web1
  web2:
    build: ./web2
    container_name: web2
  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx/reverse-proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2

  locust:
    image: locustio/locust
    container_name: locust
    ports:
      - "8089:8089"
    volumes:
      - ./load-test:/mnt/locust
    command: -f /mnt/locust/locustfile.py --host=http://reverse-proxy
    depends_on:
      - reverse-proxy